### ISSUE TITLE
Please update and merge Installation pages

### ISSUE THREAD

**Issue by richlysakowski** [opengeos/pygis#21]
Please update and merge Installation pages:

I noticed that the two installation pages are different from one another

1) https://pygis.gishub.org/installation/  ... this is more complete and has better instructions and better navigation on the upper right-hand corner, because it explains how to use conda and mamba more completely.

2) https://pygis.gishub.org/#installation ... this appears simpler and has a link to the nice YouTube video that explains things.  However, the navigation in the upper right-hand corner is missing mamba and conda detailed instructions.  

These two pages should be merged in favor of number 1) above. 

I also created

**Comment by giswqs** [comment]
Would you like to submit a pull request to fix it?
